# Site settings
title: Shoshanna's Portfolio
description: This is a portfolio website to document and share code and UX projects I've worked on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.shoshannatm.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shoshanna Thomas-McCue
user_description: "Hi, my name is Shoshanna. I'm a software developer with a passion for UX design. 
I've earned a certificate in UX design and research from General Assembly, and a Bachelor's degree 
in Software Development from Western Governors University."
user_title: Software Developer
# using Apple's Hide My Email feature for security
email: corncob_teatime_0d@icloud.com
github_username: shoshannaTM
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules']

